### ISSUE TITLE
ask hangs sometimes with block_on

### ISSUE THREAD

**Issue by thedavidmeister** [riker-rs/riker-patterns#2] opened 2018-08-22 11:41 UTC
minimum repro tests at #1 

the test runs a few thousand asks, but i've seen things hang with fewer than 5 iterations

whether it hangs is non-deterministic

AFAIK i've taken the code straight from the docs here :/

**Comment by leenozara** [comment] 2018-08-24 01:19
Thanks or testing that. I'll recreate it and see where it is hanging.

**Comment by leenozara** [comment] 2018-08-30 06:50
@thedavidmeister FYI the hanging can be recreated and the reason has been identified. Today's `0.1.6` still has the hang issue but we're closer to resolving it. Sorry it's taking time - it's been more difficult than expected to resolve. Please hang tight, it'll be fixed soon.

**Comment by leenozara** [comment] 2018-08-30 07:35
@thedavidmeister I can confirm that Riker `0.1.7` fixes this hang issue. Can you also confirm? Thanks!

**Comment by thedavidmeister** [comment] 2018-08-30 09:00
works for me in the HC branch, nice work! @leenozara

**Comment by leenozara** [comment] 2018-08-30 11:52
Closing this issue based on participants' testings.

**Closed as completed** 2018-08-30 11:51 UTC
